services:
  - type: web
    name: barberflow-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        scope: all
      - key: NODE_ENV
        value: production
      - key: BREVO_API_KEY
        scope: all
      - key: JWT_SECRET
        scope: all

  - type: web
    name: barberflow-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: VITE_API_URL
        value: https://barber-flow-2j9t.onrender.com
      - key: VITE_BOOKING_URL
        value: https://barberflow-frontend.onrender.com
