services:
  - type: web
    name: barberflow-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        scope: all
      - key: NODE_ENV
        value: production
      - key: BREVO_API_KEY
        scope: all
      - key: JWT_SECRET
        scope: all

  - type: static
    name: barberflow-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
